{%- if cookiecutter.use_code_quality == 'y' %}
[tool.black]
line-length = 120
skip_magic_trailing_comma = true

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
{%- endif %}
